project_id = "rjhtauzookkvlipvqpvr"

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.telegram-miniapp-auth]
verify_jwt = false

[functions.telegram-config]
verify_jwt = false

[functions.telegram-request-contact]
verify_jwt = false

[functions.telegram-oidc-start]
verify_jwt = false

[functions.telegram-oidc-callback]
verify_jwt = false