project_id = "rjhtauzookkvlipvqpvr"

[functions.ai-chat]
verify_jwt = false

[functions.ai-enhance]
verify_jwt = false

[functions.ai-evaluate]
verify_jwt = false

[functions.ai-generate-onboarding]
verify_jwt = false